---
name: Python package

'on':
  - pull_request
  - push

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          python -c 'import receptor_affinity; print(receptor_affinity.__version__)'
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Lint yaml files
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: true
